FROM node:14 As production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json .
COPY package-lock.json .

RUN npm install --production=false

RUN apt-get -q update && apt-get -qy install netcat

COPY . .

RUN npm run build

CMD [ "node", "server.js"]