FROM node:14 As production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/api

COPY package.json .

COPY package-lock.json .

RUN npm global install @nestjs/cli
RUN npm install --production=true

RUN apt-get -q update && apt-get -qy install netcat

COPY . .

RUN npm run build

CMD [ "sh", "-c", "typeorm migration:run && npm run start:prod" ]